const RED_FLAGS = [
  { pattern: /fast.?paced/i,             phrase: 'fast-paced',             explain: 'Chaotic environment, no processes, constant firefighting. Nobody ever says "we\'re slow-paced and chill."' },
  { pattern: /wear many hats/i,          phrase: 'wear many hats',         explain: 'You\'ll be doing 3 jobs for the price of 1. Understaffed by design.' },
  { pattern: /rock.?star|ninja|wizard|guru|unicorn/i, phrase: 'rockstar/ninja/wizard', explain: 'Bro culture. Likely toxic workplace. Run.' },
  { pattern: /competitive salary/i,      phrase: 'competitive salary',     explain: 'They won\'t tell you the number. Usually means it\'s lower than market.' },
  { pattern: /unlimited pto|unlimited leave/i, phrase: 'unlimited PTO',    explain: 'Studies show people take LESS leave with "unlimited" PTO because there\'s no baseline.' },
  { pattern: /startup (mentality|mindset|culture)/i, phrase: 'startup mentality', explain: 'Long hours, low pay, "we\'re a family" pressure. Hustle culture.' },
  { pattern: /self.?starter/i,           phrase: 'self-starter',           explain: 'Little to no onboarding. You\'ll be figuring it out alone from day 1.' },
  { pattern: /we\'re like a family|like a family/i, phrase: "we're like a family", explain: 'Expect overwork, guilt-tripping about boundaries, and emotional manipulation.' },
  { pattern: /passionate/i,              phrase: 'passionate',             explain: 'They expect you to work overtime for free because you "love the job."' },
  { pattern: /dynamic (environment|team|role)/i, phrase: 'dynamic environment', explain: 'Things change randomly with no warning. Role could be completely different in 3 months.' },
  { pattern: /hit the ground running/i,  phrase: 'hit the ground running', explain: 'No training, no handover, thrown in the deep end immediately.' },
  { pattern: /results.?driven/i,         phrase: 'results-driven',         explain: 'Pressure culture. Metrics above everything, including your wellbeing.' },
  { pattern: /flexible hours/i,          phrase: 'flexible hours',         explain: 'Often means "flexible for us" — could mean early calls, late nights, weekends.' },
  { pattern: /above and beyond/i,        phrase: 'above and beyond',       explain: 'They already expect more than your contract states.' },
  { pattern: /no (two days|day) the same/i, phrase: 'no two days the same', explain: 'Unpredictable, disorganised. Could be exciting or exhausting depending on context.' },
  { pattern: /hustle/i,                  phrase: 'hustle',                 explain: 'Overwork is celebrated here. Work-life balance is not a priority.' },
  { pattern: /scrappy/i,                 phrase: 'scrappy',                explain: 'Underfunded. Expect to do a lot with very little budget or support.' },
  { pattern: /high.?growth/i,            phrase: 'high-growth',            explain: 'Growing fast = often chaotic, roles undefined, leadership stretched thin.' },
  { pattern: /10\s*[\+\-–]?\s*years?.{0,15}(react|next\.?js|vue|svelte|flutter|kubernetes|terraform|graphql)/i, phrase: '10 years experience in modern tech', explain: 'Fake requirement — this technology hasn\'t existed for 10 years. They don\'t know what they\'re doing.' },
  { pattern: /15\s*[\+\-–]?\s*years?.{0,15}(javascript|python|java|php)/i, phrase: '15 years in a language', explain: 'Possibly unrealistic or used to filter people and lowball pay.' },
  { pattern: /overqualified/i,           phrase: 'overqualified',          explain: 'They may hire you then ignore your input because "we do things differently here."' },
  { pattern: /move fast (and)? break things/i, phrase: 'move fast and break things', explain: 'No QA, no processes, no accountability. Technical debt guaranteed.' },
  { pattern: /ownership mentality/i,     phrase: 'ownership mentality',    explain: 'They want you emotionally invested but won\'t give you actual ownership or equity.' },
  { pattern: /culture fit/i,             phrase: 'culture fit',            explain: 'Vague, subjective — can mask bias. Ask what "culture" actually means to them.' },
  { pattern: /independent worker/i,      phrase: 'independent worker',     explain: 'Minimal management support. You\'ll be invisible until something goes wrong.' },
  { pattern: /entrepreneurial spirit/i,  phrase: 'entrepreneurial spirit', explain: 'They want the drive of a founder without the equity or pay of one.' },
  { pattern: /multi.?task/i,             phrase: 'multitask',              explain: 'Juggling too many priorities is expected and normalised here.' },
  { pattern: /small but mighty/i,        phrase: 'small but mighty',       explain: 'Tiny team = everyone wears many hats and works long hours.' },
  { pattern: /global (team|company)/i,   phrase: 'global team',            explain: 'Possible early morning or late-night calls for different time zones.' },
  { pattern: /impact.?driven/i,          phrase: 'impact-driven',          explain: 'Often used to justify lower pay — "you\'re changing the world, isn\'t that enough?"' },
];

const GREEN_FLAGS = [
  { pattern: /salary range|compensation range|\$[\d,]+\s*[-–]\s*\$[\d,]+|lkr[\d,]+/i, explain: 'Transparent salary range — they respect your time and theirs.' },
  { pattern: /remote.?first/i,           explain: 'Remote-first (not just remote-friendly) = built for distributed teams.' },
  { pattern: /4.?day work week/i,        explain: '4-day work week = they take employee wellbeing seriously.' },
  { pattern: /clear (career|growth) path|promotion path/i, explain: 'Defined career growth — they invest in your future.' },
  { pattern: /mental health (day|support|benefit)/i, explain: 'Mental health support — they acknowledge employees are humans.' },
  { pattern: /learning (budget|allowance)|education budget|training budget/i, explain: 'Learning budget — they invest in your skills.' },
  { pattern: /equity|stock options|esop/i, explain: 'Equity offered — you can share in the company\'s upside.' },
  { pattern: /parental leave|maternity|paternity/i, explain: 'Parental leave mentioned — family-friendly policies.' },
  { pattern: /diversity|inclusion|belonging/i, explain: 'DEI commitment stated — broader perspective valued.' },
  { pattern: /work.?life balance/i,       explain: 'Explicitly mentions work-life balance — at least they\'re aware it matters.' },
  { pattern: /asynchronous|async.?first/i, explain: 'Async-first culture = respects your focus time, no meeting overload.' },
  { pattern: /transparent|open.?book/i,   explain: 'Claims transparency — a strong cultural signal if genuine.' },
];

const CORPORATE_SPEAK = [
  { from: /leverage/gi,             to: 'use' },
  { from: /synergize?/gi,           to: 'work together' },
  { from: /circle back/gi,          to: 'follow up' },
  { from: /bandwidth/gi,            to: 'time/capacity' },
  { from: /move the needle/gi,      to: 'make progress' },
  { from: /boil the ocean/gi,       to: 'do too much at once' },
  { from: /low.?hanging fruit/gi,   to: 'easy wins' },
  { from: /deep dive/gi,            to: 'detailed look' },
  { from: /think outside the box/gi,to: 'be creative' },
  { from: /at the end of the day/gi,to: 'ultimately' },
  { from: /take offline/gi,         to: 'discuss privately' },
  { from: /run it up the flagpole/gi,to: 'get approval' },
  { from: /ping me/gi,              to: 'message me' },
  { from: /on the same page/gi,     to: 'in agreement' },
  { from: /value.?add/gi,           to: 'useful contribution' },
  { from: /ecosystem/gi,            to: 'environment/network' },
  { from: /agile mindset/gi,        to: 'adaptable' },
  { from: /cross.?functional/gi,    to: 'working across teams' },
  { from: /stakeholders/gi,         to: 'people involved' },
  { from: /deliverables/gi,         to: 'outputs/results' },
  { from: /scalable solution/gi,    to: 'solution that can grow' },
  { from: /proactive/gi,            to: 'takes initiative' },
  { from: /action items/gi,         to: 'tasks' },
  { from: /pain points/gi,          to: 'problems' },
];
